baseURL = "https://sqlmaniak.blog/"
title = "SQL Maniak"
languageCode = "pl-pl"
theme = "sqlmaniak"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "Marcin"
  description = "Blog o SQL Server 2016-2022, monitoringu baz danych, optymalizacji zapytań oraz narzędziach PowerShell i Grafana dla administratorów"
  canonicalURL = "https://sqlmaniak.blog/"

[params.featuredScripts]
  [[params.featuredScripts.items]]
    name = "DMV Demo"
    url  = "/files/dmv-demo.sql"
  [[params.featuredScripts.items]]
    name = "PowerShell: Get-SqlServices"
    url  = "/files/Get-SqlServices.ps1"
  [[params.featuredScripts.items]]
    name = "Repo GitHub: o SQL "
    url  = "https://github.com/marcinpytlik/SQLManiak"

[params.authorProfile]
  name = "Marcin Pytlik"
  linkedin = "https://www.linkedin.com/in/sqlmaniak"
  github   = "https://github.com/marcinpytlik/SQLManiak"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    tabWidth = 4
