baseURL = "https://marcinpytlik.github.io/"
title = "SQL Maniak"
languageCode = "pl-pl"
theme = "sqlmaniak"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Marcin"
  description = "SQL Server • Monitoring • Grafana/InfluxDB • PowerShell"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    tabWidth = 4

[params.featuredScripts]
  [[params.featuredScripts.items]]
    name = "DMV Demo"
    url = "/files/dmv-demo.sql"
  [[params.featuredScripts.items]]
    name = "PowerShell: Get-SqlServices"
    url = "/files/Get-SqlServices.ps1"
  [[params.featuredScripts.items]]
    name = "Repo GitHub: SQL Monitoring"
    url = "https://github.com/marcinpytlik/sql-monitoring"

[params.authorProfile]
  name = "Marcin Pytlik"
  linkedin = "https://www.linkedin.com/in/sqlmaniak"
  github   = "https://github.com/marcinpytlik/SQLManiak"
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  canonicalURL = "http://sqlmaniak.blog/"
